# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_control.ui'
#
# Created: Thu Aug 22 16:08:33 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ControlWindow(object):
    def setupUi(self, ControlWindow):
        ControlWindow.setObjectName(_fromUtf8("ControlWindow"))
        ControlWindow.resize(748, 622)
        self.centralwidget = QtGui.QWidget(ControlWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.running_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.running_label.setFont(font)
        self.running_label.setObjectName(_fromUtf8("running_label"))
        self.horizontalLayout.addWidget(self.running_label)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tab_group = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tab_group.setFont(font)
        self.tab_group.setObjectName(_fromUtf8("tab_group"))
        self.tab_explore = QtGui.QWidget()
        self.tab_explore.setObjectName(_fromUtf8("tab_explore"))
        self.comboBox = QtGui.QComboBox(self.tab_explore)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.listWidget_2 = QtGui.QListWidget(self.tab_explore)
        self.listWidget_2.setGeometry(QtCore.QRect(170, 40, 201, 191))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.label_4 = QtGui.QLabel(self.tab_explore)
        self.label_4.setGeometry(QtCore.QRect(170, 20, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tab_group.addTab(self.tab_explore, _fromUtf8(""))
        self.tab_tc = QtGui.QWidget()
        self.tab_tc.setObjectName(_fromUtf8("tab_tc"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_tc)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.db_stop_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_stop_spnbx.setFont(font)
        self.db_stop_spnbx.setMaximum(150)
        self.db_stop_spnbx.setProperty("value", 110)
        self.db_stop_spnbx.setObjectName(_fromUtf8("db_stop_spnbx"))
        self.gridLayout_2.addWidget(self.db_stop_spnbx, 2, 2, 1, 1)
        self.freq_step_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_step_spnbx.setFont(font)
        self.freq_step_spnbx.setMaximum(100)
        self.freq_step_spnbx.setProperty("value", 1)
        self.freq_step_spnbx.setObjectName(_fromUtf8("freq_step_spnbx"))
        self.gridLayout_2.addWidget(self.freq_step_spnbx, 1, 3, 1, 1)
        self.freq_stop_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_stop_spnbx.setFont(font)
        self.freq_stop_spnbx.setMaximum(200)
        self.freq_stop_spnbx.setProperty("value", 150)
        self.freq_stop_spnbx.setObjectName(_fromUtf8("freq_stop_spnbx"))
        self.gridLayout_2.addWidget(self.freq_stop_spnbx, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 4, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 4, 1, 1)
        self.freq_start_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_start_spnbx.setFont(font)
        self.freq_start_spnbx.setMaximum(200)
        self.freq_start_spnbx.setSingleStep(5)
        self.freq_start_spnbx.setProperty("value", 5)
        self.freq_start_spnbx.setObjectName(_fromUtf8("freq_start_spnbx"))
        self.gridLayout_2.addWidget(self.freq_start_spnbx, 1, 1, 1, 1)
        self.db_step_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_step_spnbx.setFont(font)
        self.db_step_spnbx.setMaximum(50)
        self.db_step_spnbx.setProperty("value", 5)
        self.db_step_spnbx.setObjectName(_fromUtf8("db_step_spnbx"))
        self.gridLayout_2.addWidget(self.db_step_spnbx, 2, 3, 1, 1)
        self.db_start_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_start_spnbx.setFont(font)
        self.db_start_spnbx.setMaximum(150)
        self.db_start_spnbx.setSingleStep(5)
        self.db_start_spnbx.setProperty("value", 0)
        self.db_start_spnbx.setObjectName(_fromUtf8("db_start_spnbx"))
        self.gridLayout_2.addWidget(self.db_start_spnbx, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_tc)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_tc)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_tc)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_22 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.dur_spnbx_2 = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dur_spnbx_2.setFont(font)
        self.dur_spnbx_2.setMinimum(100)
        self.dur_spnbx_2.setMaximum(50000)
        self.dur_spnbx_2.setSingleStep(100)
        self.dur_spnbx_2.setProperty("value", 1000)
        self.dur_spnbx_2.setObjectName(_fromUtf8("dur_spnbx_2"))
        self.gridLayout_3.addWidget(self.dur_spnbx_2, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 5, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 3, 1, 1)
        self.aosr_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aosr_spnbx.setFont(font)
        self.aosr_spnbx.setMinimum(10)
        self.aosr_spnbx.setMaximum(1000)
        self.aosr_spnbx.setSingleStep(10)
        self.aosr_spnbx.setProperty("value", 100)
        self.aosr_spnbx.setObjectName(_fromUtf8("aosr_spnbx"))
        self.gridLayout_3.addWidget(self.aosr_spnbx, 1, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 5, 1, 1)
        self.reprate_spnbx = QtGui.QDoubleSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reprate_spnbx.setFont(font)
        self.reprate_spnbx.setMinimum(0.1)
        self.reprate_spnbx.setMaximum(10.0)
        self.reprate_spnbx.setProperty("value", 0.5)
        self.reprate_spnbx.setObjectName(_fromUtf8("reprate_spnbx"))
        self.gridLayout_3.addWidget(self.reprate_spnbx, 1, 1, 1, 1)
        self.nreps_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nreps_spnbx.setFont(font)
        self.nreps_spnbx.setMinimum(1)
        self.nreps_spnbx.setMaximum(100)
        self.nreps_spnbx.setProperty("value", 5)
        self.nreps_spnbx.setObjectName(_fromUtf8("nreps_spnbx"))
        self.gridLayout_3.addWidget(self.nreps_spnbx, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 2, 0, 1, 1)
        self.risefall_spnbx_2 = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.risefall_spnbx_2.setFont(font)
        self.risefall_spnbx_2.setMaximum(100)
        self.risefall_spnbx_2.setObjectName(_fromUtf8("risefall_spnbx_2"))
        self.gridLayout_3.addWidget(self.risefall_spnbx_2, 0, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.tab_group.addTab(self.tab_tc, _fromUtf8(""))
        self.tab_chart = QtGui.QWidget()
        self.tab_chart.setObjectName(_fromUtf8("tab_chart"))
        self.tab_group.addTab(self.tab_chart, _fromUtf8(""))
        self.tab_protocol = QtGui.QWidget()
        self.tab_protocol.setObjectName(_fromUtf8("tab_protocol"))
        self.label_2 = QtGui.QLabel(self.tab_protocol)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton = QtGui.QPushButton(self.tab_protocol)
        self.pushButton.setGeometry(QtCore.QRect(100, 260, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tableWidget = QtGui.QTableWidget(self.tab_protocol)
        self.tableWidget.setGeometry(QtCore.QRect(70, 40, 251, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.tab_group.addTab(self.tab_protocol, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tab_group)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.aochan_box = QtGui.QComboBox(self.centralwidget)
        self.aochan_box.setObjectName(_fromUtf8("aochan_box"))
        self.gridLayout_4.addWidget(self.aochan_box, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 1, 0, 1, 1)
        self.aichan_box = QtGui.QComboBox(self.centralwidget)
        self.aichan_box.setObjectName(_fromUtf8("aichan_box"))
        self.gridLayout_4.addWidget(self.aichan_box, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.aisr_spnbx = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aisr_spnbx.setFont(font)
        self.aisr_spnbx.setMinimum(1)
        self.aisr_spnbx.setMaximum(200)
        self.aisr_spnbx.setSingleStep(10)
        self.aisr_spnbx.setProperty("value", 10)
        self.aisr_spnbx.setObjectName(_fromUtf8("aisr_spnbx"))
        self.horizontalLayout_3.addWidget(self.aisr_spnbx)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.start_btn = QtGui.QPushButton(self.centralwidget)
        self.start_btn.setObjectName(_fromUtf8("start_btn"))
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.stop_btn = QtGui.QPushButton(self.centralwidget)
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.horizontalLayout_2.addWidget(self.stop_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        ControlWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ControlWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        ControlWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ControlWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ControlWindow.setStatusBar(self.statusbar)
        self.plot_dock = QtGui.QDockWidget(ControlWindow)
        self.plot_dock.setObjectName(_fromUtf8("plot_dock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.parrot_label = QtGui.QLabel(self.dockWidgetContents)
        self.parrot_label.setObjectName(_fromUtf8("parrot_label"))
        self.verticalLayout_4.addWidget(self.parrot_label)
        self.plot_dock.setWidget(self.dockWidgetContents)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.plot_dock)
        self.actionSave_Options = QtGui.QAction(ControlWindow)
        self.actionSave_Options.setObjectName(_fromUtf8("actionSave_Options"))
        self.actionSet_Calibration = QtGui.QAction(ControlWindow)
        self.actionSet_Calibration.setObjectName(_fromUtf8("actionSet_Calibration"))
        self.menuOptions.addAction(self.actionSave_Options)
        self.menuOptions.addAction(self.actionSet_Calibration)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(ControlWindow)
        self.tab_group.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionSave_Options, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launch_save_dlg)
        QtCore.QObject.connect(self.actionSet_Calibration, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launch_calibration_dlg)
        QtCore.QMetaObject.connectSlotsByName(ControlWindow)

    def retranslateUi(self, ControlWindow):
        ControlWindow.setWindowTitle(_translate("ControlWindow", "MainWindow", None))
        self.label_3.setText(_translate("ControlWindow", "Neruone Control", None))
        self.running_label.setText(_translate("ControlWindow", "OFF", None))
        self.comboBox.setItemText(0, _translate("ControlWindow", "Tone", None))
        self.comboBox.setItemText(1, _translate("ControlWindow", "FM Sweep", None))
        self.comboBox.setItemText(2, _translate("ControlWindow", "Vocalization", None))
        self.label_4.setText(_translate("ControlWindow", "History:", None))
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_explore), _translate("ControlWindow", "Explore", None))
        self.label_21.setText(_translate("ControlWindow", "dB SPL", None))
        self.label_19.setText(_translate("ControlWindow", "kHz", None))
        self.label_25.setText(_translate("ControlWindow", "Frequency", None))
        self.label_26.setText(_translate("ControlWindow", "Start", None))
        self.label_18.setText(_translate("ControlWindow", "Intensity", None))
        self.label_27.setText(_translate("ControlWindow", "Stop", None))
        self.label_28.setText(_translate("ControlWindow", "Step", None))
        self.label_22.setText(_translate("ControlWindow", "Duration", None))
        self.label_24.setText(_translate("ControlWindow", "ms", None))
        self.label_20.setText(_translate("ControlWindow", "ms", None))
        self.label_23.setText(_translate("ControlWindow", "Rep rate", None))
        self.label_15.setText(_translate("ControlWindow", "reps/s", None))
        self.label_17.setText(_translate("ControlWindow", "Gen. Sample rate", None))
        self.label_16.setText(_translate("ControlWindow", "kHz", None))
        self.label_31.setText(_translate("ControlWindow", "Reps", None))
        self.label_14.setText(_translate("ControlWindow", "Rise fall time", None))
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_tc), _translate("ControlWindow", "Tuning Curve", None))
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_chart), _translate("ControlWindow", "Chart", None))
        self.label_2.setText(_translate("ControlWindow", "Experiment Protocol:", None))
        self.pushButton.setText(_translate("ControlWindow", "Edit...", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ControlWindow", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ControlWindow", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("ControlWindow", "3", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ControlWindow", "Stim", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ControlWindow", "Reps", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("ControlWindow", "mouse_scream", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("ControlWindow", "3", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("ControlWindow", "FM Sweep", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("ControlWindow", "3", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("ControlWindow", "white noise", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("ControlWindow", "5", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_protocol), _translate("ControlWindow", "Experiment", None))
        self.label_30.setText(_translate("ControlWindow", "AI channel", None))
        self.label_29.setText(_translate("ControlWindow", "Stim channel", None))
        self.label.setText(_translate("ControlWindow", "Acq. Sample rate", None))
        self.label_7.setText(_translate("ControlWindow", "kHz", None))
        self.start_btn.setText(_translate("ControlWindow", "Start", None))
        self.stop_btn.setText(_translate("ControlWindow", "Abort", None))
        self.menuOptions.setTitle(_translate("ControlWindow", "Options", None))
        self.parrot_label.setText(_translate("ControlWindow", "This is a late parrot", None))
        self.actionSave_Options.setText(_translate("ControlWindow", "Save Options...", None))
        self.actionSet_Calibration.setText(_translate("ControlWindow", "Set Calibration...", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ControlWindow = QtGui.QMainWindow()
    ui = Ui_ControlWindow()
    ui.setupUi(ControlWindow)
    ControlWindow.show()
    sys.exit(app.exec_())

