# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_control.ui'
#
# Created: Wed Sep 18 02:59:00 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ControlWindow(object):
    def setupUi(self, ControlWindow):
        ControlWindow.setObjectName(_fromUtf8("ControlWindow"))
        ControlWindow.resize(967, 802)
        self.centralwidget = QtGui.QWidget(ControlWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.running_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.running_label.setFont(font)
        self.running_label.setObjectName(_fromUtf8("running_label"))
        self.horizontalLayout.addWidget(self.running_label)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tab_group = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tab_group.setFont(font)
        self.tab_group.setObjectName(_fromUtf8("tab_group"))
        self.tab_explore = QtGui.QWidget()
        self.tab_explore.setObjectName(_fromUtf8("tab_explore"))
        self.explore_stim_type_cmbbx = QtGui.QComboBox(self.tab_explore)
        self.explore_stim_type_cmbbx.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.explore_stim_type_cmbbx.setObjectName(_fromUtf8("explore_stim_type_cmbbx"))
        self.explore_stim_type_cmbbx.addItem(_fromUtf8(""))
        self.explore_stim_type_cmbbx.addItem(_fromUtf8(""))
        self.explore_stim_type_cmbbx.addItem(_fromUtf8(""))
        self.listWidget_2 = QtGui.QListWidget(self.tab_explore)
        self.listWidget_2.setGeometry(QtCore.QRect(530, 40, 201, 191))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.label_4 = QtGui.QLabel(self.tab_explore)
        self.label_4.setGeometry(QtCore.QRect(530, 20, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_39 = QtGui.QLabel(self.tab_explore)
        self.label_39.setGeometry(QtCore.QRect(20, 450, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.nreps_spnbx_2 = QtGui.QSpinBox(self.tab_explore)
        self.nreps_spnbx_2.setGeometry(QtCore.QRect(80, 470, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nreps_spnbx_2.setFont(font)
        self.nreps_spnbx_2.setMinimum(0)
        self.nreps_spnbx_2.setMaximum(100)
        self.nreps_spnbx_2.setProperty("value", 5)
        self.nreps_spnbx_2.setObjectName(_fromUtf8("nreps_spnbx_2"))
        self.stackedWidget = QtGui.QStackedWidget(self.tab_explore)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 50, 471, 331))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 2, 1, 1)
        self.reprate_spnbx_2 = QtGui.QDoubleSpinBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reprate_spnbx_2.setFont(font)
        self.reprate_spnbx_2.setMinimum(0.1)
        self.reprate_spnbx_2.setMaximum(10.0)
        self.reprate_spnbx_2.setProperty("value", 0.5)
        self.reprate_spnbx_2.setObjectName(_fromUtf8("reprate_spnbx_2"))
        self.gridLayout_5.addWidget(self.reprate_spnbx_2, 3, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.page)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_5.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_5.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_5.addWidget(self.label_40, 4, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_5.addWidget(self.label_38, 5, 2, 1, 1)
        self.aosr_spnbx_2 = QtGui.QSpinBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aosr_spnbx_2.setFont(font)
        self.aosr_spnbx_2.setMinimum(10)
        self.aosr_spnbx_2.setMaximum(1000)
        self.aosr_spnbx_2.setSingleStep(10)
        self.aosr_spnbx_2.setProperty("value", 100)
        self.aosr_spnbx_2.setObjectName(_fromUtf8("aosr_spnbx_2"))
        self.gridLayout_5.addWidget(self.aosr_spnbx_2, 5, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_5.addWidget(self.label_37, 5, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_5.addWidget(self.label_34, 4, 2, 1, 1)
        self.risefall_spnbx_3 = QtGui.QSpinBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.risefall_spnbx_3.setFont(font)
        self.risefall_spnbx_3.setMaximum(100)
        self.risefall_spnbx_3.setObjectName(_fromUtf8("risefall_spnbx_3"))
        self.gridLayout_5.addWidget(self.risefall_spnbx_3, 4, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 2, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_5.addWidget(self.label_35, 3, 0, 1, 1)
        self.dur_spnbx_3 = QtGui.QSpinBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dur_spnbx_3.setFont(font)
        self.dur_spnbx_3.setMinimum(100)
        self.dur_spnbx_3.setMaximum(50000)
        self.dur_spnbx_3.setSingleStep(100)
        self.dur_spnbx_3.setProperty("value", 1000)
        self.dur_spnbx_3.setObjectName(_fromUtf8("dur_spnbx_3"))
        self.gridLayout_5.addWidget(self.dur_spnbx_3, 2, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 2, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_5.addWidget(self.label_36, 3, 2, 1, 1)
        self.label_42 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 1, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.page)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_5.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 1, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_63 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_8.addWidget(self.label_63, 1, 4, 1, 1)
        self.freq_stop_spnbx_2 = QtGui.QSpinBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_stop_spnbx_2.setFont(font)
        self.freq_stop_spnbx_2.setMaximum(200)
        self.freq_stop_spnbx_2.setProperty("value", 150)
        self.freq_stop_spnbx_2.setObjectName(_fromUtf8("freq_stop_spnbx_2"))
        self.gridLayout_8.addWidget(self.freq_stop_spnbx_2, 1, 2, 1, 1)
        self.label_64 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_8.addWidget(self.label_64, 1, 0, 1, 1)
        self.freq_start_spnbx_2 = QtGui.QSpinBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_start_spnbx_2.setFont(font)
        self.freq_start_spnbx_2.setMaximum(200)
        self.freq_start_spnbx_2.setSingleStep(5)
        self.freq_start_spnbx_2.setProperty("value", 5)
        self.freq_start_spnbx_2.setObjectName(_fromUtf8("freq_start_spnbx_2"))
        self.gridLayout_8.addWidget(self.freq_start_spnbx_2, 1, 1, 1, 1)
        self.label_67 = QtGui.QLabel(self.page_2)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_8.addWidget(self.label_67, 0, 2, 1, 1)
        self.label_65 = QtGui.QLabel(self.page_2)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_8.addWidget(self.label_65, 0, 1, 1, 1)
        self.label_68 = QtGui.QLabel(self.page_2)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_8.addWidget(self.label_68, 0, 3, 1, 1)
        self.freq_step_spnbx_2 = QtGui.QSpinBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_step_spnbx_2.setFont(font)
        self.freq_step_spnbx_2.setMaximum(100)
        self.freq_step_spnbx_2.setProperty("value", 1)
        self.freq_step_spnbx_2.setObjectName(_fromUtf8("freq_step_spnbx_2"))
        self.gridLayout_8.addWidget(self.freq_step_spnbx_2, 1, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.risefall_spnbx_4 = QtGui.QSpinBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.risefall_spnbx_4.setFont(font)
        self.risefall_spnbx_4.setMaximum(100)
        self.risefall_spnbx_4.setObjectName(_fromUtf8("risefall_spnbx_4"))
        self.gridLayout_6.addWidget(self.risefall_spnbx_4, 3, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_6.addWidget(self.label_47, 3, 2, 1, 1)
        self.reprate_spnbx_3 = QtGui.QDoubleSpinBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reprate_spnbx_3.setFont(font)
        self.reprate_spnbx_3.setMinimum(0.1)
        self.reprate_spnbx_3.setMaximum(10.0)
        self.reprate_spnbx_3.setProperty("value", 0.5)
        self.reprate_spnbx_3.setObjectName(_fromUtf8("reprate_spnbx_3"))
        self.gridLayout_6.addWidget(self.reprate_spnbx_3, 2, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_6.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_6.addWidget(self.label_45, 4, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_6.addWidget(self.label_46, 4, 0, 1, 1)
        self.aosr_spnbx_3 = QtGui.QSpinBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aosr_spnbx_3.setFont(font)
        self.aosr_spnbx_3.setMinimum(10)
        self.aosr_spnbx_3.setMaximum(1000)
        self.aosr_spnbx_3.setSingleStep(10)
        self.aosr_spnbx_3.setProperty("value", 100)
        self.aosr_spnbx_3.setObjectName(_fromUtf8("aosr_spnbx_3"))
        self.gridLayout_6.addWidget(self.aosr_spnbx_3, 4, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_6.addWidget(self.label_48, 1, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_6.addWidget(self.label_49, 2, 0, 1, 1)
        self.dur_spnbx_4 = QtGui.QSpinBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dur_spnbx_4.setFont(font)
        self.dur_spnbx_4.setMinimum(100)
        self.dur_spnbx_4.setMaximum(50000)
        self.dur_spnbx_4.setSingleStep(100)
        self.dur_spnbx_4.setProperty("value", 1000)
        self.dur_spnbx_4.setObjectName(_fromUtf8("dur_spnbx_4"))
        self.gridLayout_6.addWidget(self.dur_spnbx_4, 1, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_6.addWidget(self.label_50, 1, 2, 1, 1)
        self.label_51 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_6.addWidget(self.label_51, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 0, 2, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.page_2)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_6.addWidget(self.spinBox_4, 0, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_6.addWidget(self.label_52, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.wavrootdir_lnedt = QtGui.QLineEdit(self.page_3)
        self.wavrootdir_lnedt.setObjectName(_fromUtf8("wavrootdir_lnedt"))
        self.horizontalLayout_6.addWidget(self.wavrootdir_lnedt)
        self.wavrootdir_btn = QtGui.QPushButton(self.page_3)
        self.wavrootdir_btn.setObjectName(_fromUtf8("wavrootdir_btn"))
        self.horizontalLayout_6.addWidget(self.wavrootdir_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.splitter_2 = QtGui.QSplitter(self.page_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.filetree_view = QtGui.QTreeView(self.splitter)
        self.filetree_view.setObjectName(_fromUtf8("filetree_view"))
        self.filelist_view = QtGui.QListView(self.splitter)
        self.filelist_view.setObjectName(_fromUtf8("filelist_view"))
        self.spec_preview = ImageWidget(self.splitter_2)
        self.spec_preview.setObjectName(_fromUtf8("spec_preview"))
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.stackedWidget.addWidget(self.page_3)
        self.tab_group.addTab(self.tab_explore, _fromUtf8(""))
        self.tab_chart = QtGui.QWidget()
        self.tab_chart.setObjectName(_fromUtf8("tab_chart"))
        self.tab_group.addTab(self.tab_chart, _fromUtf8(""))
        self.tab_tc = QtGui.QWidget()
        self.tab_tc.setObjectName(_fromUtf8("tab_tc"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_tc)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.db_stop_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_stop_spnbx.setFont(font)
        self.db_stop_spnbx.setMaximum(150)
        self.db_stop_spnbx.setProperty("value", 110)
        self.db_stop_spnbx.setObjectName(_fromUtf8("db_stop_spnbx"))
        self.gridLayout_2.addWidget(self.db_stop_spnbx, 2, 2, 1, 1)
        self.freq_step_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_step_spnbx.setFont(font)
        self.freq_step_spnbx.setMaximum(100)
        self.freq_step_spnbx.setProperty("value", 1)
        self.freq_step_spnbx.setObjectName(_fromUtf8("freq_step_spnbx"))
        self.gridLayout_2.addWidget(self.freq_step_spnbx, 1, 3, 1, 1)
        self.freq_stop_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_stop_spnbx.setFont(font)
        self.freq_stop_spnbx.setMaximum(200)
        self.freq_stop_spnbx.setProperty("value", 150)
        self.freq_stop_spnbx.setObjectName(_fromUtf8("freq_stop_spnbx"))
        self.gridLayout_2.addWidget(self.freq_stop_spnbx, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 4, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 4, 1, 1)
        self.freq_start_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_start_spnbx.setFont(font)
        self.freq_start_spnbx.setMaximum(200)
        self.freq_start_spnbx.setSingleStep(5)
        self.freq_start_spnbx.setProperty("value", 5)
        self.freq_start_spnbx.setObjectName(_fromUtf8("freq_start_spnbx"))
        self.gridLayout_2.addWidget(self.freq_start_spnbx, 1, 1, 1, 1)
        self.db_step_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_step_spnbx.setFont(font)
        self.db_step_spnbx.setMaximum(50)
        self.db_step_spnbx.setProperty("value", 5)
        self.db_step_spnbx.setObjectName(_fromUtf8("db_step_spnbx"))
        self.gridLayout_2.addWidget(self.db_step_spnbx, 2, 3, 1, 1)
        self.db_start_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_start_spnbx.setFont(font)
        self.db_start_spnbx.setMaximum(150)
        self.db_start_spnbx.setSingleStep(5)
        self.db_start_spnbx.setProperty("value", 0)
        self.db_start_spnbx.setObjectName(_fromUtf8("db_start_spnbx"))
        self.gridLayout_2.addWidget(self.db_start_spnbx, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_tc)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_tc)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_tc)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_22 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.dur_spnbx_2 = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dur_spnbx_2.setFont(font)
        self.dur_spnbx_2.setMinimum(100)
        self.dur_spnbx_2.setMaximum(50000)
        self.dur_spnbx_2.setSingleStep(100)
        self.dur_spnbx_2.setProperty("value", 1000)
        self.dur_spnbx_2.setObjectName(_fromUtf8("dur_spnbx_2"))
        self.gridLayout_3.addWidget(self.dur_spnbx_2, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 5, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 3, 1, 1)
        self.aosr_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aosr_spnbx.setFont(font)
        self.aosr_spnbx.setMinimum(10)
        self.aosr_spnbx.setMaximum(1000)
        self.aosr_spnbx.setSingleStep(10)
        self.aosr_spnbx.setProperty("value", 100)
        self.aosr_spnbx.setObjectName(_fromUtf8("aosr_spnbx"))
        self.gridLayout_3.addWidget(self.aosr_spnbx, 1, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_tc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 5, 1, 1)
        self.reprate_spnbx = QtGui.QDoubleSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reprate_spnbx.setFont(font)
        self.reprate_spnbx.setMinimum(0.1)
        self.reprate_spnbx.setMaximum(10.0)
        self.reprate_spnbx.setProperty("value", 0.5)
        self.reprate_spnbx.setObjectName(_fromUtf8("reprate_spnbx"))
        self.gridLayout_3.addWidget(self.reprate_spnbx, 1, 1, 1, 1)
        self.nreps_spnbx = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nreps_spnbx.setFont(font)
        self.nreps_spnbx.setMinimum(1)
        self.nreps_spnbx.setMaximum(100)
        self.nreps_spnbx.setProperty("value", 5)
        self.nreps_spnbx.setObjectName(_fromUtf8("nreps_spnbx"))
        self.gridLayout_3.addWidget(self.nreps_spnbx, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 2, 0, 1, 1)
        self.risefall_spnbx_2 = QtGui.QSpinBox(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.risefall_spnbx_2.setFont(font)
        self.risefall_spnbx_2.setMaximum(100)
        self.risefall_spnbx_2.setObjectName(_fromUtf8("risefall_spnbx_2"))
        self.gridLayout_3.addWidget(self.risefall_spnbx_2, 0, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_tc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.tab_group.addTab(self.tab_tc, _fromUtf8(""))
        self.tab_protocol = QtGui.QWidget()
        self.tab_protocol.setObjectName(_fromUtf8("tab_protocol"))
        self.label_2 = QtGui.QLabel(self.tab_protocol)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton = QtGui.QPushButton(self.tab_protocol)
        self.pushButton.setGeometry(QtCore.QRect(100, 260, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tableWidget = QtGui.QTableWidget(self.tab_protocol)
        self.tableWidget.setGeometry(QtCore.QRect(70, 40, 251, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.listWidget = QtGui.QListWidget(self.tab_protocol)
        self.listWidget.setGeometry(QtCore.QRect(420, 60, 256, 192))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label_8 = QtGui.QLabel(self.tab_protocol)
        self.label_8.setGeometry(QtCore.QRect(420, 40, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tab_group.addTab(self.tab_protocol, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tab_group)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.aochan_box = QtGui.QComboBox(self.centralwidget)
        self.aochan_box.setObjectName(_fromUtf8("aochan_box"))
        self.gridLayout_4.addWidget(self.aochan_box, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 1, 0, 1, 1)
        self.aichan_box = QtGui.QComboBox(self.centralwidget)
        self.aichan_box.setObjectName(_fromUtf8("aichan_box"))
        self.gridLayout_4.addWidget(self.aichan_box, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.aisr_spnbx = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aisr_spnbx.setFont(font)
        self.aisr_spnbx.setMinimum(1)
        self.aisr_spnbx.setMaximum(500)
        self.aisr_spnbx.setSingleStep(10)
        self.aisr_spnbx.setProperty("value", 100)
        self.aisr_spnbx.setObjectName(_fromUtf8("aisr_spnbx"))
        self.gridLayout.addWidget(self.aisr_spnbx, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.windowsz_spnbx = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.windowsz_spnbx.setFont(font)
        self.windowsz_spnbx.setMinimum(50)
        self.windowsz_spnbx.setMaximum(10000)
        self.windowsz_spnbx.setSingleStep(50)
        self.windowsz_spnbx.setProperty("value", 100)
        self.windowsz_spnbx.setObjectName(_fromUtf8("windowsz_spnbx"))
        self.gridLayout.addWidget(self.windowsz_spnbx, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.start_btn = QtGui.QPushButton(self.centralwidget)
        self.start_btn.setObjectName(_fromUtf8("start_btn"))
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.stop_btn = QtGui.QPushButton(self.centralwidget)
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.horizontalLayout_2.addWidget(self.stop_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        ControlWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ControlWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        ControlWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ControlWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ControlWindow.setStatusBar(self.statusbar)
        self.plot_dock = QtGui.QDockWidget(ControlWindow)
        self.plot_dock.setObjectName(_fromUtf8("plot_dock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.display = ProtocolDisplay(self.dockWidgetContents)
        self.display.setObjectName(_fromUtf8("display"))
        self.verticalLayout_4.addWidget(self.display)
        self.plot_dock.setWidget(self.dockWidgetContents)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.plot_dock)
        self.actionSave_Options = QtGui.QAction(ControlWindow)
        self.actionSave_Options.setObjectName(_fromUtf8("actionSave_Options"))
        self.actionSet_Calibration = QtGui.QAction(ControlWindow)
        self.actionSet_Calibration.setObjectName(_fromUtf8("actionSet_Calibration"))
        self.menuOptions.addAction(self.actionSave_Options)
        self.menuOptions.addAction(self.actionSet_Calibration)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(ControlWindow)
        self.tab_group.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionSave_Options, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launch_save_dlg)
        QtCore.QObject.connect(self.actionSet_Calibration, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launch_calibration_dlg)
        QtCore.QObject.connect(self.explore_stim_type_cmbbx, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.filetree_view, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), ControlWindow.wavdir_selected)
        QtCore.QObject.connect(self.wavrootdir_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlWindow.browse_wavdirs)
        QtCore.QObject.connect(self.filelist_view, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), ControlWindow.wavfile_selected)
        QtCore.QObject.connect(self.filelist_view, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), ControlWindow.wavfile_clicked)
        QtCore.QMetaObject.connectSlotsByName(ControlWindow)

    def retranslateUi(self, ControlWindow):
        ControlWindow.setWindowTitle(_translate("ControlWindow", "MainWindow", None))
        self.label_3.setText(_translate("ControlWindow", "Neruone Control", None))
        self.running_label.setText(_translate("ControlWindow", "OFF", None))
        self.explore_stim_type_cmbbx.setItemText(0, _translate("ControlWindow", "Tone", None))
        self.explore_stim_type_cmbbx.setItemText(1, _translate("ControlWindow", "FM Sweep", None))
        self.explore_stim_type_cmbbx.setItemText(2, _translate("ControlWindow", "Vocalization", None))
        self.label_4.setText(_translate("ControlWindow", "History:", None))
        self.label_39.setText(_translate("ControlWindow", "Reps", None))
        self.label_5.setText(_translate("ControlWindow", "kHz", None))
        self.label_41.setText(_translate("ControlWindow", "Frequency", None))
        self.label_40.setText(_translate("ControlWindow", "Rise fall time", None))
        self.label_38.setText(_translate("ControlWindow", "kHz", None))
        self.label_37.setText(_translate("ControlWindow", "Gen. Sample rate", None))
        self.label_34.setText(_translate("ControlWindow", "ms", None))
        self.label_32.setText(_translate("ControlWindow", "Duration", None))
        self.label_35.setText(_translate("ControlWindow", "Rep rate", None))
        self.label_33.setText(_translate("ControlWindow", "ms", None))
        self.label_36.setText(_translate("ControlWindow", "reps/s", None))
        self.label_42.setText(_translate("ControlWindow", "Intensity", None))
        self.label_6.setText(_translate("ControlWindow", "dB SPL", None))
        self.label_63.setText(_translate("ControlWindow", "kHz", None))
        self.label_64.setText(_translate("ControlWindow", "Frequency", None))
        self.label_67.setText(_translate("ControlWindow", "Stop", None))
        self.label_65.setText(_translate("ControlWindow", "Start", None))
        self.label_68.setText(_translate("ControlWindow", "Step", None))
        self.label_47.setText(_translate("ControlWindow", "ms", None))
        self.label_44.setText(_translate("ControlWindow", "Rise fall time", None))
        self.label_45.setText(_translate("ControlWindow", "kHz", None))
        self.label_46.setText(_translate("ControlWindow", "Gen. Sample rate", None))
        self.label_48.setText(_translate("ControlWindow", "Duration", None))
        self.label_49.setText(_translate("ControlWindow", "Rep rate", None))
        self.label_50.setText(_translate("ControlWindow", "ms", None))
        self.label_51.setText(_translate("ControlWindow", "reps/s", None))
        self.label_9.setText(_translate("ControlWindow", "dB SPL", None))
        self.label_52.setText(_translate("ControlWindow", "Intensity", None))
        self.wavrootdir_btn.setText(_translate("ControlWindow", "change", None))
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_explore), _translate("ControlWindow", "Explore", None))
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_chart), _translate("ControlWindow", "Chart", None))
        self.label_21.setText(_translate("ControlWindow", "dB SPL", None))
        self.label_19.setText(_translate("ControlWindow", "kHz", None))
        self.label_25.setText(_translate("ControlWindow", "Frequency", None))
        self.label_26.setText(_translate("ControlWindow", "Start", None))
        self.label_18.setText(_translate("ControlWindow", "Intensity", None))
        self.label_27.setText(_translate("ControlWindow", "Stop", None))
        self.label_28.setText(_translate("ControlWindow", "Step", None))
        self.label_22.setText(_translate("ControlWindow", "Duration", None))
        self.label_24.setText(_translate("ControlWindow", "ms", None))
        self.label_20.setText(_translate("ControlWindow", "ms", None))
        self.label_23.setText(_translate("ControlWindow", "Rep rate", None))
        self.label_15.setText(_translate("ControlWindow", "reps/s", None))
        self.label_17.setText(_translate("ControlWindow", "Gen. Sample rate", None))
        self.label_16.setText(_translate("ControlWindow", "kHz", None))
        self.label_31.setText(_translate("ControlWindow", "Reps", None))
        self.label_14.setText(_translate("ControlWindow", "Rise fall time", None))
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_tc), _translate("ControlWindow", "Tuning Curve", None))
        self.label_2.setText(_translate("ControlWindow", "Experiment Protocol:", None))
        self.pushButton.setText(_translate("ControlWindow", "Edit...", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ControlWindow", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ControlWindow", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("ControlWindow", "3", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ControlWindow", "Stim", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ControlWindow", "Reps", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("ControlWindow", "mouse_scream", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("ControlWindow", "3", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("ControlWindow", "FM Sweep", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("ControlWindow", "3", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("ControlWindow", "white noise", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("ControlWindow", "5", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("ControlWindow", "HIstory", None))
        self.tab_group.setTabText(self.tab_group.indexOf(self.tab_protocol), _translate("ControlWindow", "Experiment", None))
        self.label_30.setText(_translate("ControlWindow", "AI channel", None))
        self.label_29.setText(_translate("ControlWindow", "Stim channel", None))
        self.label.setText(_translate("ControlWindow", "Acq. Sample rate", None))
        self.label_7.setText(_translate("ControlWindow", "kHz", None))
        self.label_10.setText(_translate("ControlWindow", "Window size", None))
        self.label_11.setText(_translate("ControlWindow", "ms", None))
        self.start_btn.setText(_translate("ControlWindow", "Start", None))
        self.stop_btn.setText(_translate("ControlWindow", "Abort", None))
        self.menuOptions.setTitle(_translate("ControlWindow", "Options", None))
        self.actionSave_Options.setText(_translate("ControlWindow", "Save Options...", None))
        self.actionSet_Calibration.setText(_translate("ControlWindow", "Set Calibration...", None))

from audiolab.plotting.chacoplots import ImageWidget
from audiolab.plotting.protocoldisplay import ProtocolDisplay

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ControlWindow = QtGui.QMainWindow()
    ui = Ui_ControlWindow()
    ui.setupUi(ControlWindow)
    ControlWindow.show()
    sys.exit(app.exec_())

