# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tuning_curve.ui'
#
# Created: Mon Aug 19 11:33:48 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TuningCurve(object):
    def setupUi(self, TuningCurve):
        TuningCurve.setObjectName(_fromUtf8("TuningCurve"))
        TuningCurve.resize(418, 242)
        self.verticalLayout = QtGui.QVBoxLayout(TuningCurve)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.db_stop_spnbx = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_stop_spnbx.setFont(font)
        self.db_stop_spnbx.setMaximum(150)
        self.db_stop_spnbx.setProperty("value", 110)
        self.db_stop_spnbx.setObjectName(_fromUtf8("db_stop_spnbx"))
        self.gridLayout_2.addWidget(self.db_stop_spnbx, 2, 2, 1, 1)
        self.freq_step_spnbx = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_step_spnbx.setFont(font)
        self.freq_step_spnbx.setMaximum(100)
        self.freq_step_spnbx.setProperty("value", 1)
        self.freq_step_spnbx.setObjectName(_fromUtf8("freq_step_spnbx"))
        self.gridLayout_2.addWidget(self.freq_step_spnbx, 1, 3, 1, 1)
        self.freq_stop_spnbx = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_stop_spnbx.setFont(font)
        self.freq_stop_spnbx.setMaximum(200)
        self.freq_stop_spnbx.setProperty("value", 150)
        self.freq_stop_spnbx.setObjectName(_fromUtf8("freq_stop_spnbx"))
        self.gridLayout_2.addWidget(self.freq_stop_spnbx, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 4, 1, 1)
        self.label_19 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 4, 1, 1)
        self.freq_start_spnbx = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_start_spnbx.setFont(font)
        self.freq_start_spnbx.setMaximum(200)
        self.freq_start_spnbx.setSingleStep(5)
        self.freq_start_spnbx.setProperty("value", 5)
        self.freq_start_spnbx.setObjectName(_fromUtf8("freq_start_spnbx"))
        self.gridLayout_2.addWidget(self.freq_start_spnbx, 1, 1, 1, 1)
        self.db_step_spnbx = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_step_spnbx.setFont(font)
        self.db_step_spnbx.setMaximum(50)
        self.db_step_spnbx.setProperty("value", 5)
        self.db_step_spnbx.setObjectName(_fromUtf8("db_step_spnbx"))
        self.gridLayout_2.addWidget(self.db_step_spnbx, 2, 3, 1, 1)
        self.db_start_spnbx = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.db_start_spnbx.setFont(font)
        self.db_start_spnbx.setMaximum(150)
        self.db_start_spnbx.setSingleStep(5)
        self.db_start_spnbx.setProperty("value", 0)
        self.db_start_spnbx.setObjectName(_fromUtf8("db_start_spnbx"))
        self.gridLayout_2.addWidget(self.db_start_spnbx, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(TuningCurve)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(TuningCurve)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(TuningCurve)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_22 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.dur_spnbx_2 = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dur_spnbx_2.setFont(font)
        self.dur_spnbx_2.setMinimum(100)
        self.dur_spnbx_2.setMaximum(50000)
        self.dur_spnbx_2.setSingleStep(100)
        self.dur_spnbx_2.setProperty("value", 1000)
        self.dur_spnbx_2.setObjectName(_fromUtf8("dur_spnbx_2"))
        self.gridLayout_3.addWidget(self.dur_spnbx_2, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 5, 1, 1)
        self.label_23 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 3, 1, 1)
        self.sr_spnbx_2 = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sr_spnbx_2.setFont(font)
        self.sr_spnbx_2.setMinimum(10)
        self.sr_spnbx_2.setMaximum(1000)
        self.sr_spnbx_2.setSingleStep(10)
        self.sr_spnbx_2.setProperty("value", 100)
        self.sr_spnbx_2.setObjectName(_fromUtf8("sr_spnbx_2"))
        self.gridLayout_3.addWidget(self.sr_spnbx_2, 1, 4, 1, 1)
        self.label_16 = QtGui.QLabel(TuningCurve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 5, 1, 1)
        self.reprate_spnbx = QtGui.QDoubleSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reprate_spnbx.setFont(font)
        self.reprate_spnbx.setMinimum(0.1)
        self.reprate_spnbx.setMaximum(10.0)
        self.reprate_spnbx.setProperty("value", 0.5)
        self.reprate_spnbx.setObjectName(_fromUtf8("reprate_spnbx"))
        self.gridLayout_3.addWidget(self.reprate_spnbx, 1, 1, 1, 1)
        self.nreps_spnbx = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nreps_spnbx.setFont(font)
        self.nreps_spnbx.setMinimum(1)
        self.nreps_spnbx.setMaximum(100)
        self.nreps_spnbx.setProperty("value", 5)
        self.nreps_spnbx.setObjectName(_fromUtf8("nreps_spnbx"))
        self.gridLayout_3.addWidget(self.nreps_spnbx, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(TuningCurve)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 5, 1, 1)
        self.label = QtGui.QLabel(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 2, 3, 1, 1)
        self.aisr_spnbx_2 = QtGui.QSpinBox(TuningCurve)
        self.aisr_spnbx_2.setMinimum(1)
        self.aisr_spnbx_2.setMaximum(200)
        self.aisr_spnbx_2.setSingleStep(10)
        self.aisr_spnbx_2.setProperty("value", 10)
        self.aisr_spnbx_2.setObjectName(_fromUtf8("aisr_spnbx_2"))
        self.gridLayout_3.addWidget(self.aisr_spnbx_2, 2, 4, 1, 1)
        self.risefall_spnbx_2 = QtGui.QSpinBox(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.risefall_spnbx_2.setFont(font)
        self.risefall_spnbx_2.setMaximum(100)
        self.risefall_spnbx_2.setObjectName(_fromUtf8("risefall_spnbx_2"))
        self.gridLayout_3.addWidget(self.risefall_spnbx_2, 0, 4, 1, 1)
        self.label_14 = QtGui.QLabel(TuningCurve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.start_btn = QtGui.QPushButton(TuningCurve)
        self.start_btn.setObjectName(_fromUtf8("start_btn"))
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.stop_btn = QtGui.QPushButton(TuningCurve)
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.horizontalLayout_2.addWidget(self.stop_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(TuningCurve)
        QtCore.QMetaObject.connectSlotsByName(TuningCurve)

    def retranslateUi(self, TuningCurve):
        TuningCurve.setWindowTitle(_translate("TuningCurve", "Form", None))
        self.label_21.setText(_translate("TuningCurve", "dB SPL", None))
        self.label_19.setText(_translate("TuningCurve", "kHz", None))
        self.label_25.setText(_translate("TuningCurve", "Frequency", None))
        self.label_26.setText(_translate("TuningCurve", "Start", None))
        self.label_18.setText(_translate("TuningCurve", "Intensity", None))
        self.label_27.setText(_translate("TuningCurve", "Stop", None))
        self.label_28.setText(_translate("TuningCurve", "Step", None))
        self.label_22.setText(_translate("TuningCurve", "Duration", None))
        self.label_24.setText(_translate("TuningCurve", "ms", None))
        self.label_20.setText(_translate("TuningCurve", "ms", None))
        self.label_23.setText(_translate("TuningCurve", "Rep rate", None))
        self.label_15.setText(_translate("TuningCurve", "reps/s", None))
        self.label_17.setText(_translate("TuningCurve", "Gen. Sample rate", None))
        self.label_16.setText(_translate("TuningCurve", "kHz", None))
        self.label_31.setText(_translate("TuningCurve", "Reps", None))
        self.label_7.setText(_translate("TuningCurve", "kHz", None))
        self.label.setText(_translate("TuningCurve", "Acq. Sample rate", None))
        self.label_14.setText(_translate("TuningCurve", "Rise fall time", None))
        self.start_btn.setText(_translate("TuningCurve", "Start", None))
        self.stop_btn.setText(_translate("TuningCurve", "Abort", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TuningCurve = QtGui.QWidget()
    ui = Ui_TuningCurve()
    ui.setupUi(TuningCurve)
    TuningCurve.show()
    sys.exit(app.exec_())

