from calibration_dlg import CalibrationDialog
from channel_dlg import ChannelDialog
from saving_dlg import SavingDialog 
from scale_dlg import ScaleDialog
from specgram_dlg import SpecDialog
from comment_dlg import CellCommentDialog
from view_dlg import ViewSettingsDialog
from vocal_path_dlg import VocalPathDialog
from advanced_dlg import AdvancedOptionsDialog
