# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_control.ui'
#
# Created: Mon Jun  8 17:27:22 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ControlWindow(object):
    def setupUi(self, ControlWindow):
        ControlWindow.setObjectName(_fromUtf8("ControlWindow"))
        ControlWindow.resize(1223, 744)
        self.centralwidget = QtGui.QWidget(ControlWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.reviewLbl = QtGui.QLabel(self.centralwidget)
        self.reviewLbl.setText(_fromUtf8(""))
        self.reviewLbl.setObjectName(_fromUtf8("reviewLbl"))
        self.horizontalLayout.addWidget(self.reviewLbl)
        self.runningLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runningLabel.sizePolicy().hasHeightForWidth())
        self.runningLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.runningLabel.setFont(font)
        self.runningLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runningLabel.setObjectName(_fromUtf8("runningLabel"))
        self.horizontalLayout.addWidget(self.runningLabel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.tabGroup = QtGui.QTabWidget(self.centralwidget)
        self.tabGroup.setObjectName(_fromUtf8("tabGroup"))
        self.tabExplore = QtGui.QWidget()
        self.tabExplore.setObjectName(_fromUtf8("tabExplore"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabExplore)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.exploreStimEditor = ExploreStimulusEditor(self.tabExplore)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exploreStimEditor.sizePolicy().hasHeightForWidth())
        self.exploreStimEditor.setSizePolicy(sizePolicy)
        self.exploreStimEditor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.exploreStimEditor.setFrameShadow(QtGui.QFrame.Raised)
        self.exploreStimEditor.setObjectName(_fromUtf8("exploreStimEditor"))
        self.verticalLayout_9.addWidget(self.exploreStimEditor)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.save_explore_ckbx = QtGui.QCheckBox(self.tabExplore)
        self.save_explore_ckbx.setEnabled(False)
        self.save_explore_ckbx.setObjectName(_fromUtf8("save_explore_ckbx"))
        self.gridLayout_7.addWidget(self.save_explore_ckbx, 1, 0, 1, 2)
        self.label_20 = QtGui.QLabel(self.tabExplore)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 1)
        self.overAttenLbl = QtGui.QLabel(self.tabExplore)
        self.overAttenLbl.setObjectName(_fromUtf8("overAttenLbl"))
        self.gridLayout_7.addWidget(self.overAttenLbl, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.tabExplore)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 0, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.tabGroup.addTab(self.tabExplore, _fromUtf8(""))
        self.tabProtocol = QtGui.QWidget()
        self.tabProtocol.setObjectName(_fromUtf8("tabProtocol"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabProtocol)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.tabProtocol)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.protocolView = ProtocolView(self.tabProtocol)
        self.protocolView.setObjectName(_fromUtf8("protocolView"))
        self.verticalLayout_5.addWidget(self.protocolView)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.stimulusChoices = StimulusLabelTable(self.tabProtocol)
        self.stimulusChoices.setObjectName(_fromUtf8("stimulusChoices"))
        self.horizontalLayout_9.addWidget(self.stimulusChoices)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.tabProtocol)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.tabGroup.addTab(self.tabProtocol, _fromUtf8(""))
        self.tabCalibrate = QtGui.QWidget()
        self.tabCalibrate.setObjectName(_fromUtf8("tabCalibrate"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabCalibrate)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.calibrationWidget = CalibrationWidget(self.tabCalibrate)
        self.calibrationWidget.setObjectName(_fromUtf8("calibrationWidget"))
        self.verticalLayout.addWidget(self.calibrationWidget)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.overAttenLbl_2 = QtGui.QLabel(self.tabCalibrate)
        self.overAttenLbl_2.setObjectName(_fromUtf8("overAttenLbl_2"))
        self.gridLayout_3.addWidget(self.overAttenLbl_2, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tabCalibrate)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.refToneLbl = QtGui.QLabel(self.tabCalibrate)
        self.refToneLbl.setObjectName(_fromUtf8("refToneLbl"))
        self.horizontalLayout_10.addWidget(self.refToneLbl)
        self.label_4 = QtGui.QLabel(self.tabCalibrate)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_10.addWidget(self.label_4)
        self.refDbSpnbx = SmartSpinBox(self.tabCalibrate)
        self.refDbSpnbx.setEnabled(False)
        self.refDbSpnbx.setAlignment(QtCore.Qt.AlignCenter)
        self.refDbSpnbx.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.refDbSpnbx.setMaximum(120.0)
        self.refDbSpnbx.setObjectName(_fromUtf8("refDbSpnbx"))
        self.horizontalLayout_10.addWidget(self.refDbSpnbx)
        self.label_15 = QtGui.QLabel(self.tabCalibrate)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_9 = QtGui.QLabel(self.tabCalibrate)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_12.addWidget(self.label_9)
        self.mphoneSensSpnbx = QtGui.QDoubleSpinBox(self.tabCalibrate)
        self.mphoneSensSpnbx.setEnabled(False)
        self.mphoneSensSpnbx.setAlignment(QtCore.Qt.AlignCenter)
        self.mphoneSensSpnbx.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.mphoneSensSpnbx.setDecimals(4)
        self.mphoneSensSpnbx.setObjectName(_fromUtf8("mphoneSensSpnbx"))
        self.horizontalLayout_12.addWidget(self.mphoneSensSpnbx)
        self.label_18 = QtGui.QLabel(self.tabCalibrate)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.mphoneDBSpnbx = QtGui.QDoubleSpinBox(self.tabCalibrate)
        self.mphoneDBSpnbx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mphoneDBSpnbx.sizePolicy().hasHeightForWidth())
        self.mphoneDBSpnbx.setSizePolicy(sizePolicy)
        self.mphoneDBSpnbx.setAlignment(QtCore.Qt.AlignCenter)
        self.mphoneDBSpnbx.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.mphoneDBSpnbx.setDecimals(0)
        self.mphoneDBSpnbx.setMaximum(120.0)
        self.mphoneDBSpnbx.setObjectName(_fromUtf8("mphoneDBSpnbx"))
        self.horizontalLayout_12.addWidget(self.mphoneDBSpnbx)
        self.label_22 = QtGui.QLabel(self.tabCalibrate)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_12.addWidget(self.label_22)
        self.mphoneCalBtn = QtGui.QPushButton(self.tabCalibrate)
        self.mphoneCalBtn.setObjectName(_fromUtf8("mphoneCalBtn"))
        self.horizontalLayout_12.addWidget(self.mphoneCalBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.tabGroup.addTab(self.tabCalibrate, _fromUtf8(""))
        self.tabReview = QtGui.QWidget()
        self.tabReview.setObjectName(_fromUtf8("tabReview"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tabReview)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.reviewer = QDataReviewer(self.tabReview)
        self.reviewer.setObjectName(_fromUtf8("reviewer"))
        self.verticalLayout_13.addWidget(self.reviewer)
        self.tabGroup.addTab(self.tabReview, _fromUtf8(""))
        self.verticalLayout_12.addWidget(self.tabGroup)
        self.protocolProgressBar = QtGui.QProgressBar(self.centralwidget)
        self.protocolProgressBar.setEnabled(True)
        self.protocolProgressBar.setProperty("value", 0)
        self.protocolProgressBar.setObjectName(_fromUtf8("protocolProgressBar"))
        self.verticalLayout_12.addWidget(self.protocolProgressBar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.chanNumLbl = QtGui.QLabel(self.centralwidget)
        self.chanNumLbl.setObjectName(_fromUtf8("chanNumLbl"))
        self.gridLayout_4.addWidget(self.chanNumLbl, 1, 1, 1, 1)
        self.aochanBox = QtGui.QComboBox(self.centralwidget)
        self.aochanBox.setObjectName(_fromUtf8("aochanBox"))
        self.gridLayout_4.addWidget(self.aochanBox, 0, 1, 1, 2)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.aichanBtn = QtGui.QPushButton(self.centralwidget)
        self.aichanBtn.setObjectName(_fromUtf8("aichanBtn"))
        self.gridLayout_4.addWidget(self.aichanBtn, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 3, 0, 1, 1)
        self.aifsSpnbx = SmartSpinBox(self.centralwidget)
        self.aifsSpnbx.setDecimals(3)
        self.aifsSpnbx.setMaximum(500000.0)
        self.aifsSpnbx.setObjectName(_fromUtf8("aifsSpnbx"))
        self.gridLayout.addWidget(self.aifsSpnbx, 0, 1, 1, 1)
        self.binszSpnbx = SmartSpinBox(self.centralwidget)
        self.binszSpnbx.setDecimals(3)
        self.binszSpnbx.setMaximum(3.0)
        self.binszSpnbx.setSingleStep(0.001)
        self.binszSpnbx.setProperty("value", 0.001)
        self.binszSpnbx.setObjectName(_fromUtf8("binszSpnbx"))
        self.gridLayout.addWidget(self.binszSpnbx, 3, 1, 1, 1)
        self.reprateSpnbx = QtGui.QDoubleSpinBox(self.centralwidget)
        self.reprateSpnbx.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.reprateSpnbx.setPrefix(_fromUtf8(""))
        self.reprateSpnbx.setMinimum(0.1)
        self.reprateSpnbx.setMaximum(10.0)
        self.reprateSpnbx.setProperty("value", 0.5)
        self.reprateSpnbx.setObjectName(_fromUtf8("reprateSpnbx"))
        self.gridLayout.addWidget(self.reprateSpnbx, 4, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 4, 0, 1, 1)
        self.windowszSpnbx = SmartSpinBox(self.centralwidget)
        self.windowszSpnbx.setDecimals(3)
        self.windowszSpnbx.setMaximum(3.0)
        self.windowszSpnbx.setSingleStep(0.001)
        self.windowszSpnbx.setProperty("value", 0.1)
        self.windowszSpnbx.setObjectName(_fromUtf8("windowszSpnbx"))
        self.gridLayout.addWidget(self.windowszSpnbx, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.trigchanBox = QtGui.QComboBox(self.centralwidget)
        self.trigchanBox.setObjectName(_fromUtf8("trigchanBox"))
        self.gridLayout_5.addWidget(self.trigchanBox, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.modeCmbx = QtGui.QComboBox(self.centralwidget)
        self.modeCmbx.setObjectName(_fromUtf8("modeCmbx"))
        self.modeCmbx.addItem(_fromUtf8(""))
        self.modeCmbx.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.modeCmbx, 0, 1, 1, 1)
        self.trigCkbx = QtGui.QCheckBox(self.centralwidget)
        self.trigCkbx.setObjectName(_fromUtf8("trigCkbx"))
        self.gridLayout_5.addWidget(self.trigCkbx, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.HLine)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.currentCalLbl = QtGui.QLabel(self.centralwidget)
        self.currentCalLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentCalLbl.setWordWrap(True)
        self.currentCalLbl.setObjectName(_fromUtf8("currentCalLbl"))
        self.gridLayout_2.addWidget(self.currentCalLbl, 0, 1, 1, 1)
        self.dataFileLbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataFileLbl.sizePolicy().hasHeightForWidth())
        self.dataFileLbl.setSizePolicy(sizePolicy)
        self.dataFileLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dataFileLbl.setObjectName(_fromUtf8("dataFileLbl"))
        self.gridLayout_2.addWidget(self.dataFileLbl, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.startChartBtn = QtGui.QPushButton(self.centralwidget)
        self.startChartBtn.setObjectName(_fromUtf8("startChartBtn"))
        self.horizontalLayout_8.addWidget(self.startChartBtn)
        self.stopChartBtn = QtGui.QPushButton(self.centralwidget)
        self.stopChartBtn.setObjectName(_fromUtf8("stopChartBtn"))
        self.horizontalLayout_8.addWidget(self.stopChartBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.startBtn = QtGui.QPushButton(self.centralwidget)
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.horizontalLayout_2.addWidget(self.startBtn)
        self.stopBtn = QtGui.QPushButton(self.centralwidget)
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.horizontalLayout_2.addWidget(self.stopBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        ControlWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ControlWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1223, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuShow = QtGui.QMenu(self.menuView)
        self.menuShow.setObjectName(_fromUtf8("menuShow"))
        ControlWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ControlWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ControlWindow.setStatusBar(self.statusbar)
        self.plotDock = PlotDockWidget(ControlWindow)
        self.plotDock.setObjectName(_fromUtf8("plotDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.plotDock.setWidget(self.dockWidgetContents)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.plotDock)
        self.psthDock = QtGui.QDockWidget(ControlWindow)
        self.psthDock.setObjectName(_fromUtf8("psthDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.PSTHContainer = QtGui.QWidget(self.dockWidgetContents_2)
        self.PSTHContainer.setObjectName(_fromUtf8("PSTHContainer"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.PSTHContainer)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.psth = PSTHWidget(self.PSTHContainer)
        self.psth.setObjectName(_fromUtf8("psth"))
        self.verticalLayout_6.addWidget(self.psth)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_11 = QtGui.QLabel(self.PSTHContainer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.PSTHContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_9.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.PSTHContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 1, 0, 1, 1)
        self.spikeLatencyLbl = QtGui.QLabel(self.PSTHContainer)
        self.spikeLatencyLbl.setObjectName(_fromUtf8("spikeLatencyLbl"))
        self.gridLayout_9.addWidget(self.spikeLatencyLbl, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.PSTHContainer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_9.addWidget(self.label_7, 1, 3, 1, 1)
        self.spikeRateLbl = QtGui.QLabel(self.PSTHContainer)
        self.spikeRateLbl.setObjectName(_fromUtf8("spikeRateLbl"))
        self.gridLayout_9.addWidget(self.spikeRateLbl, 1, 4, 1, 1)
        self.spikeAvgLbl = QtGui.QLabel(self.PSTHContainer)
        self.spikeAvgLbl.setObjectName(_fromUtf8("spikeAvgLbl"))
        self.gridLayout_9.addWidget(self.spikeAvgLbl, 0, 4, 1, 1)
        self.spikeTotalLbl = QtGui.QLabel(self.PSTHContainer)
        self.spikeTotalLbl.setObjectName(_fromUtf8("spikeTotalLbl"))
        self.gridLayout_9.addWidget(self.spikeTotalLbl, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.PSTHContainer)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.psthStartField = SmartSpinBox(self.groupBox)
        self.psthStartField.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.psthStartField.setObjectName(_fromUtf8("psthStartField"))
        self.horizontalLayout_13.addWidget(self.psthStartField)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.psthStopField = SmartSpinBox(self.groupBox)
        self.psthStopField.setEnabled(False)
        self.psthStopField.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.psthStopField.setObjectName(_fromUtf8("psthStopField"))
        self.horizontalLayout_13.addWidget(self.psthStopField)
        self.psthMaxBox = QtGui.QCheckBox(self.groupBox)
        self.psthMaxBox.setChecked(True)
        self.psthMaxBox.setObjectName(_fromUtf8("psthMaxBox"))
        self.horizontalLayout_13.addWidget(self.psthMaxBox)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_10.addWidget(self.PSTHContainer)
        self.psthDock.setWidget(self.dockWidgetContents_2)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.psthDock)
        self.progressDock = QtGui.QDockWidget(ControlWindow)
        self.progressDock.setObjectName(_fromUtf8("progressDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.progressDock.setWidget(self.dockWidgetContents_3)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.progressDock)
        self.log_dock = QtGui.QDockWidget(ControlWindow)
        self.log_dock.setObjectName(_fromUtf8("log_dock"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.logTxedt = QtGui.QPlainTextEdit(self.dockWidgetContents_4)
        self.logTxedt.setReadOnly(True)
        self.logTxedt.setObjectName(_fromUtf8("logTxedt"))
        self.verticalLayout_7.addWidget(self.logTxedt)
        self.log_dock.setWidget(self.dockWidgetContents_4)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.log_dock)
        self.detail_dock = QtGui.QDockWidget(ControlWindow)
        self.detail_dock.setObjectName(_fromUtf8("detail_dock"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.stimDetails = StimDetailWidget(self.dockWidgetContents_5)
        self.stimDetails.setObjectName(_fromUtf8("stimDetails"))
        self.verticalLayout_11.addWidget(self.stimDetails)
        self.detail_dock.setWidget(self.dockWidgetContents_5)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.detail_dock)
        self.runComment = QtGui.QDockWidget(ControlWindow)
        self.runComment.setObjectName(_fromUtf8("runComment"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_21 = QtGui.QLabel(self.dockWidgetContents_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_11.addWidget(self.label_21)
        self.cellIDLbl = QtGui.QLabel(self.dockWidgetContents_6)
        self.cellIDLbl.setObjectName(_fromUtf8("cellIDLbl"))
        self.horizontalLayout_11.addWidget(self.cellIDLbl)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.commentTxtEdt = QtGui.QPlainTextEdit(self.dockWidgetContents_6)
        self.commentTxtEdt.setObjectName(_fromUtf8("commentTxtEdt"))
        self.verticalLayout_8.addWidget(self.commentTxtEdt)
        self.runComment.setWidget(self.dockWidgetContents_6)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.runComment)
        self.responseSpl = QtGui.QDockWidget(ControlWindow)
        self.responseSpl.setObjectName(_fromUtf8("responseSpl"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.dockWidgetContents_7)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.splLayout = QtGui.QGridLayout()
        self.splLayout.setObjectName(_fromUtf8("splLayout"))
        self.widget = QtGui.QWidget(self.dockWidgetContents_7)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.splLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.verticalLayout_14.addLayout(self.splLayout)
        self.responseSpl.setWidget(self.dockWidgetContents_7)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.responseSpl)
        self.timerDock = QtGui.QDockWidget(ControlWindow)
        self.timerDock.setObjectName(_fromUtf8("timerDock"))
        self.timerWidget = TimerWidget()
        self.timerWidget.setObjectName(_fromUtf8("timerWidget"))
        self.timerDock.setWidget(self.timerWidget)
        ControlWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.timerDock)
        self.actionSave_Options = QtGui.QAction(ControlWindow)
        self.actionSave_Options.setObjectName(_fromUtf8("actionSave_Options"))
        self.actionSet_Calibration = QtGui.QAction(ControlWindow)
        self.actionSet_Calibration.setObjectName(_fromUtf8("actionSet_Calibration"))
        self.actionSet_Scale = QtGui.QAction(ControlWindow)
        self.actionSet_Scale.setObjectName(_fromUtf8("actionSet_Scale"))
        self.actionShow_Data_display = QtGui.QAction(ControlWindow)
        self.actionShow_Data_display.setObjectName(_fromUtf8("actionShow_Data_display"))
        self.actionShow_PSTH = QtGui.QAction(ControlWindow)
        self.actionShow_PSTH.setObjectName(_fromUtf8("actionShow_PSTH"))
        self.actionSpectrogram_Parameters = QtGui.QAction(ControlWindow)
        self.actionSpectrogram_Parameters.setObjectName(_fromUtf8("actionSpectrogram_Parameters"))
        self.actionShow_Progress = QtGui.QAction(ControlWindow)
        self.actionShow_Progress.setObjectName(_fromUtf8("actionShow_Progress"))
        self.actionShow_Log = QtGui.QAction(ControlWindow)
        self.actionShow_Log.setObjectName(_fromUtf8("actionShow_Log"))
        self.actionShow_Stimulus_Details = QtGui.QAction(ControlWindow)
        self.actionShow_Stimulus_Details.setObjectName(_fromUtf8("actionShow_Stimulus_Details"))
        self.actionView_Settings = QtGui.QAction(ControlWindow)
        self.actionView_Settings.setObjectName(_fromUtf8("actionView_Settings"))
        self.actionData_Display = QtGui.QAction(ControlWindow)
        self.actionData_Display.setObjectName(_fromUtf8("actionData_Display"))
        self.actionPSTH = QtGui.QAction(ControlWindow)
        self.actionPSTH.setObjectName(_fromUtf8("actionPSTH"))
        self.actionProgress = QtGui.QAction(ControlWindow)
        self.actionProgress.setObjectName(_fromUtf8("actionProgress"))
        self.actionLog = QtGui.QAction(ControlWindow)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionStimulus_Details = QtGui.QAction(ControlWindow)
        self.actionStimulus_Details.setObjectName(_fromUtf8("actionStimulus_Details"))
        self.actionSet_Cell_ID = QtGui.QAction(ControlWindow)
        self.actionSet_Cell_ID.setObjectName(_fromUtf8("actionSet_Cell_ID"))
        self.actionComment = QtGui.QAction(ControlWindow)
        self.actionComment.setObjectName(_fromUtf8("actionComment"))
        self.actionTimer = QtGui.QAction(ControlWindow)
        self.actionTimer.setObjectName(_fromUtf8("actionTimer"))
        self.actionResponse_SPL = QtGui.QAction(ControlWindow)
        self.actionResponse_SPL.setObjectName(_fromUtf8("actionResponse_SPL"))
        self.actionVocalization_paths = QtGui.QAction(ControlWindow)
        self.actionVocalization_paths.setObjectName(_fromUtf8("actionVocalization_paths"))
        self.actionAdvanced = QtGui.QAction(ControlWindow)
        self.actionAdvanced.setObjectName(_fromUtf8("actionAdvanced"))
        self.menuOptions.addAction(self.actionSave_Options)
        self.menuOptions.addAction(self.actionSet_Calibration)
        self.menuOptions.addAction(self.actionSet_Scale)
        self.menuOptions.addAction(self.actionSpectrogram_Parameters)
        self.menuOptions.addAction(self.actionSet_Cell_ID)
        self.menuOptions.addAction(self.actionVocalization_paths)
        self.menuOptions.addAction(self.actionAdvanced)
        self.menuShow.addAction(self.actionData_Display)
        self.menuShow.addAction(self.actionPSTH)
        self.menuShow.addAction(self.actionProgress)
        self.menuShow.addAction(self.actionLog)
        self.menuShow.addAction(self.actionStimulus_Details)
        self.menuShow.addAction(self.actionComment)
        self.menuShow.addAction(self.actionTimer)
        self.menuShow.addAction(self.actionResponse_SPL)
        self.menuView.addAction(self.actionView_Settings)
        self.menuView.addAction(self.menuShow.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(ControlWindow)
        self.tabGroup.setCurrentIndex(2)
        QtCore.QObject.connect(self.actionSave_Options, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchSaveDlg)
        QtCore.QObject.connect(self.actionSet_Calibration, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchCalibrationDlg)
        QtCore.QObject.connect(self.actionSet_Scale, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchScaleDlg)
        QtCore.QObject.connect(self.actionData_Display, QtCore.SIGNAL(_fromUtf8("triggered()")), self.plotDock.showNormal)
        QtCore.QObject.connect(self.actionPSTH, QtCore.SIGNAL(_fromUtf8("triggered()")), self.psthDock.showNormal)
        QtCore.QObject.connect(self.actionSpectrogram_Parameters, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchSpecgramDlg)
        QtCore.QObject.connect(self.modeCmbx, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), ControlWindow.modeToggled)
        QtCore.QObject.connect(self.actionProgress, QtCore.SIGNAL(_fromUtf8("triggered()")), self.progressDock.showNormal)
        QtCore.QObject.connect(self.tabGroup, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), ControlWindow.tabChanged)
        QtCore.QObject.connect(self.actionLog, QtCore.SIGNAL(_fromUtf8("triggered()")), self.log_dock.showNormal)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlWindow.clearProtocol)
        QtCore.QObject.connect(self.actionStimulus_Details, QtCore.SIGNAL(_fromUtf8("triggered()")), self.detail_dock.showNormal)
        QtCore.QObject.connect(self.actionView_Settings, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchViewDlg)
        QtCore.QObject.connect(self.refDbSpnbx, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), ControlWindow.updateCalDb)
        QtCore.QObject.connect(self.mphoneSensSpnbx, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), ControlWindow.updateMicrophoneCalibration)
        QtCore.QObject.connect(self.mphoneCalBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlWindow.mphoneCalibrate)
        QtCore.QObject.connect(self.mphoneDBSpnbx, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), ControlWindow.updateMicrophoneCalibration)
        QtCore.QObject.connect(self.actionSet_Cell_ID, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchCellDlg)
        QtCore.QObject.connect(self.actionComment, QtCore.SIGNAL(_fromUtf8("triggered()")), self.runComment.showNormal)
        QtCore.QObject.connect(self.actionTimer, QtCore.SIGNAL(_fromUtf8("triggered()")), self.timerDock.showNormal)
        QtCore.QObject.connect(self.modeCmbx, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), ControlWindow.setTriggerEnable)
        QtCore.QObject.connect(self.actionResponse_SPL, QtCore.SIGNAL(_fromUtf8("triggered()")), self.responseSpl.showNormal)
        QtCore.QObject.connect(self.psthMaxBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.psthStopField.setDisabled)
        QtCore.QObject.connect(self.actionVocalization_paths, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchVocalPaths)
        QtCore.QObject.connect(self.aichanBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), ControlWindow.launchChannelDlg)
        QtCore.QObject.connect(self.actionAdvanced, QtCore.SIGNAL(_fromUtf8("triggered()")), ControlWindow.launchAdvancedDlg)
        QtCore.QMetaObject.connectSlotsByName(ControlWindow)

    def retranslateUi(self, ControlWindow):
        ControlWindow.setWindowTitle(_translate("ControlWindow", "SPARKLE", None))
        self.label_3.setToolTip(_translate("ControlWindow", "SONIC SPARKLE HIGH FIVE!!!!!", None))
        self.label_3.setText(_translate("ControlWindow", "SPARKLE", None))
        self.runningLabel.setText(_translate("ControlWindow", "OFF", None))
        self.save_explore_ckbx.setText(_translate("ControlWindow", "Save Explore Recording", None))
        self.label_20.setText(_translate("ControlWindow", "Undesired Attenuation:", None))
        self.overAttenLbl.setToolTip(_translate("ControlWindow", "Stimulus had to be scaled down by this amount to be generated", None))
        self.overAttenLbl.setText(_translate("ControlWindow", "0", None))
        self.label_23.setText(_translate("ControlWindow", "dB", None))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.tabExplore), _translate("ControlWindow", "Explore", None))
        self.label_2.setText(_translate("ControlWindow", "Experiment Protocol:", None))
        self.pushButton.setToolTip(_translate("ControlWindow", "Remove all tests", None))
        self.pushButton.setText(_translate("ControlWindow", "Clear Protocol", None))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.tabProtocol), _translate("ControlWindow", "Experiment", None))
        self.overAttenLbl_2.setText(_translate("ControlWindow", "0", None))
        self.label_19.setText(_translate("ControlWindow", "undesired attenuation", None))
        self.refToneLbl.setText(_translate("ControlWindow", "Intensity at ? kHz and ?V", None))
        self.label_4.setText(_translate("ControlWindow", "=", None))
        self.refDbSpnbx.setToolTip(_translate("ControlWindow", "intensity recorded at microphone", None))
        self.label_15.setText(_translate("ControlWindow", "dB SPL", None))
        self.label_9.setText(_translate("ControlWindow", "Microphone sensitivity", None))
        self.mphoneSensSpnbx.setToolTip(_translate("ControlWindow", "Resultant amplitude of microphone measurement", None))
        self.label_18.setText(_translate("ControlWindow", "V at", None))
        self.mphoneDBSpnbx.setToolTip(_translate("ControlWindow", "intensity of microphone calibration device", None))
        self.label_22.setText(_translate("ControlWindow", "dB SPL", None))
        self.mphoneCalBtn.setToolTip(_translate("ControlWindow", "Start recording microphone calibration tone", None))
        self.mphoneCalBtn.setText(_translate("ControlWindow", "Calibrate Mic", None))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.tabCalibrate), _translate("ControlWindow", "Calibration", None))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.tabReview), _translate("ControlWindow", "Review", None))
        self.label_29.setText(_translate("ControlWindow", "Stimulus channel", None))
        self.chanNumLbl.setText(_translate("ControlWindow", "0", None))
        self.aochanBox.setToolTip(_translate("ControlWindow", "Output channel (AO#)", None))
        self.label_24.setText(_translate("ControlWindow", "Recording channels :", None))
        self.aichanBtn.setText(_translate("ControlWindow", "choose...", None))
        self.label.setText(_translate("ControlWindow", "Acq. Sample rate", None))
        self.label_10.setText(_translate("ControlWindow", "Window size", None))
        self.label_43.setText(_translate("ControlWindow", "Spike bin size", None))
        self.aifsSpnbx.setToolTip(_translate("ControlWindow", "Recording sampling rate", None))
        self.binszSpnbx.setToolTip(_translate("ControlWindow", "Time bin duration for detected spikes for raster and PSTH", None))
        self.reprateSpnbx.setToolTip(_translate("ControlWindow", "Rate of recording window repetitions", None))
        self.reprateSpnbx.setSuffix(_translate("ControlWindow", " reps/s", None))
        self.label_35.setText(_translate("ControlWindow", "Rep rate", None))
        self.label_17.setText(_translate("ControlWindow", "Mode", None))
        self.modeCmbx.setToolTip(_translate("ControlWindow", "Mode of acquisition to use", None))
        self.modeCmbx.setItemText(0, _translate("ControlWindow", "Windowed", None))
        self.modeCmbx.setItemText(1, _translate("ControlWindow", "Chart", None))
        self.trigCkbx.setText(_translate("ControlWindow", "Trigger", None))
        self.label_8.setText(_translate("ControlWindow", "Calibration:", None))
        self.currentCalLbl.setText(_translate("ControlWindow", "None", None))
        self.dataFileLbl.setText(_translate("ControlWindow", "None", None))
        self.label_14.setText(_translate("ControlWindow", "Data File:", None))
        self.startChartBtn.setText(_translate("ControlWindow", "Start Chart", None))
        self.stopChartBtn.setText(_translate("ControlWindow", "Stop Chart", None))
        self.startBtn.setToolTip(_translate("ControlWindow", "Begins acquisition with current settings", None))
        self.startBtn.setText(_translate("ControlWindow", "Start", None))
        self.stopBtn.setText(_translate("ControlWindow", "Stop", None))
        self.menuOptions.setTitle(_translate("ControlWindow", "Options", None))
        self.menuView.setTitle(_translate("ControlWindow", "View", None))
        self.menuShow.setTitle(_translate("ControlWindow", "Show", None))
        self.plotDock.setWindowTitle(_translate("ControlWindow", "Data Display", None))
        self.psthDock.setWindowTitle(_translate("ControlWindow", "PSTH", None))
        self.label_11.setToolTip(_translate("ControlWindow", "Total no. of spikes over repetitions", None))
        self.label_11.setText(_translate("ControlWindow", "Total :", None))
        self.label_16.setToolTip(_translate("ControlWindow", "Mean no. of spikes per unique stimulus", None))
        self.label_16.setText(_translate("ControlWindow", "Average : ", None))
        self.label_5.setToolTip(_translate("ControlWindow", "Mean time of first spike", None))
        self.label_5.setText(_translate("ControlWindow", "Latency (ms) : ", None))
        self.spikeLatencyLbl.setText(_translate("ControlWindow", "0", None))
        self.label_7.setToolTip(_translate("ControlWindow", "Mean no. spikes per window", None))
        self.label_7.setText(_translate("ControlWindow", "Rate :", None))
        self.spikeRateLbl.setText(_translate("ControlWindow", "0", None))
        self.spikeAvgLbl.setText(_translate("ControlWindow", "0", None))
        self.spikeTotalLbl.setText(_translate("ControlWindow", "0", None))
        self.groupBox.setTitle(_translate("ControlWindow", "subwindow", None))
        self.label_6.setText(_translate("ControlWindow", "start:", None))
        self.label_13.setText(_translate("ControlWindow", "end:", None))
        self.psthMaxBox.setText(_translate("ControlWindow", "max", None))
        self.progressDock.setWindowTitle(_translate("ControlWindow", "Progress", None))
        self.log_dock.setWindowTitle(_translate("ControlWindow", "Log", None))
        self.detail_dock.setWindowTitle(_translate("ControlWindow", "Stimulus Details", None))
        self.runComment.setWindowTitle(_translate("ControlWindow", "Comment", None))
        self.label_21.setText(_translate("ControlWindow", "Cell ID:", None))
        self.cellIDLbl.setText(_translate("ControlWindow", "0", None))
        self.responseSpl.setWindowTitle(_translate("ControlWindow", "Response dB SPL", None))
        self.timerDock.setWindowTitle(_translate("ControlWindow", "Timer", None))
        self.actionSave_Options.setText(_translate("ControlWindow", "Change Data File...", None))
        self.actionSet_Calibration.setText(_translate("ControlWindow", "Calibration Parameters...", None))
        self.actionSet_Scale.setText(_translate("ControlWindow", "Set Scale...", None))
        self.actionShow_Data_display.setText(_translate("ControlWindow", "Show Data Display", None))
        self.actionShow_PSTH.setText(_translate("ControlWindow", "Show PSTH", None))
        self.actionSpectrogram_Parameters.setText(_translate("ControlWindow", "Spectrogram Parameters...", None))
        self.actionShow_Progress.setText(_translate("ControlWindow", "Show Progress", None))
        self.actionShow_Log.setText(_translate("ControlWindow", "Show Log", None))
        self.actionShow_Stimulus_Details.setText(_translate("ControlWindow", "Show Stimulus Details", None))
        self.actionView_Settings.setText(_translate("ControlWindow", "View Settings...", None))
        self.actionData_Display.setText(_translate("ControlWindow", "Data Display", None))
        self.actionPSTH.setText(_translate("ControlWindow", "PSTH", None))
        self.actionProgress.setText(_translate("ControlWindow", "Progress", None))
        self.actionLog.setText(_translate("ControlWindow", "Log", None))
        self.actionStimulus_Details.setText(_translate("ControlWindow", "Stimulus Details", None))
        self.actionSet_Cell_ID.setText(_translate("ControlWindow", "Set Cell ID", None))
        self.actionComment.setText(_translate("ControlWindow", "Comment", None))
        self.actionTimer.setText(_translate("ControlWindow", "Timer", None))
        self.actionResponse_SPL.setText(_translate("ControlWindow", "response SPL", None))
        self.actionVocalization_paths.setText(_translate("ControlWindow", "Vocalization paths...", None))
        self.actionAdvanced.setText(_translate("ControlWindow", "Advanced...", None))

from sparkle.gui.calibration_widget import CalibrationWidget
from sparkle.gui.plotdock import PlotDockWidget
from sparkle.gui.qprotocol import ProtocolView
from sparkle.gui.stim.stim_detail import StimDetailWidget
from sparkle.gui.timer_widget import TimerWidget
from sparkle.gui.data_review import QDataReviewer
from sparkle.gui.stim.explore_stim_editor import ExploreStimulusEditor
from sparkle.gui.stim.stimulus_label import StimulusLabelTable
from sparkle.gui.stim.smart_spinbox import SmartSpinBox
from sparkle.gui.plotting.pyqtgraph_widgets import PSTHWidget
