# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\calibration_widget.ui'
#
# Created: Thu Mar 27 15:22:02 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CalibrationWidget(object):
    def setupUi(self, CalibrationWidget):
        CalibrationWidget.setObjectName(_fromUtf8("CalibrationWidget"))
        CalibrationWidget.resize(732, 253)
        self.verticalLayout = QtGui.QVBoxLayout(CalibrationWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.calgroup = QtGui.QGroupBox(CalibrationWidget)
        self.calgroup.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setKerning(True)
        self.calgroup.setFont(font)
        self.calgroup.setTitle(_fromUtf8(""))
        self.calgroup.setFlat(False)
        self.calgroup.setCheckable(False)
        self.calgroup.setObjectName(_fromUtf8("calgroup"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.calgroup)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.savecal_ckbx = QtGui.QRadioButton(self.calgroup)
        self.savecal_ckbx.setChecked(True)
        self.savecal_ckbx.setObjectName(_fromUtf8("savecal_ckbx"))
        self.horizontalLayout_4.addWidget(self.savecal_ckbx)
        self.applycal_ckbx = QtGui.QRadioButton(self.calgroup)
        self.applycal_ckbx.setObjectName(_fromUtf8("applycal_ckbx"))
        self.horizontalLayout_4.addWidget(self.applycal_ckbx)
        self.verticalLayout.addWidget(self.calgroup)
        self.groupBox = QtGui.QGroupBox(CalibrationWidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tc_radio = QtGui.QRadioButton(self.groupBox)
        self.tc_radio.setObjectName(_fromUtf8("tc_radio"))
        self.horizontalLayout.addWidget(self.tc_radio)
        self.noise_radio = QtGui.QRadioButton(self.groupBox)
        self.noise_radio.setObjectName(_fromUtf8("noise_radio"))
        self.horizontalLayout.addWidget(self.noise_radio)
        self.chirp_radio = QtGui.QRadioButton(self.groupBox)
        self.chirp_radio.setObjectName(_fromUtf8("chirp_radio"))
        self.horizontalLayout.addWidget(self.chirp_radio)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(CalibrationWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setMargin(9)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.aiv_lbl = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.aiv_lbl.setFont(font)
        self.aiv_lbl.setObjectName(_fromUtf8("aiv_lbl"))
        self.gridLayout.addWidget(self.aiv_lbl, 2, 1, 1, 1)
        self.label2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 3, 1, 1)
        self.flabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.flabel.setFont(font)
        self.flabel.setObjectName(_fromUtf8("flabel"))
        self.gridLayout.addWidget(self.flabel, 0, 1, 1, 1)
        self.label0 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label0.setFont(font)
        self.label0.setObjectName(_fromUtf8("label0"))
        self.gridLayout.addWidget(self.label0, 1, 0, 1, 1)
        self.label3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label3.setFont(font)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 2, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 4, 1, 1)
        self.fftpeak_lbl = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fftpeak_lbl.setFont(font)
        self.fftpeak_lbl.setObjectName(_fromUtf8("fftpeak_lbl"))
        self.gridLayout.addWidget(self.fftpeak_lbl, 1, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.dblabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dblabel.setFont(font)
        self.dblabel.setObjectName(_fromUtf8("dblabel"))
        self.gridLayout.addWidget(self.dblabel, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.db_lbl = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db_lbl.setFont(font)
        self.db_lbl.setObjectName(_fromUtf8("db_lbl"))
        self.gridLayout.addWidget(self.db_lbl, 3, 1, 1, 1)
        self.label4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label4.setFont(font)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 3, 0, 1, 1)
        self.label1 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 2, 0, 1, 1)
        self.avo_lbl = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avo_lbl.setFont(font)
        self.avo_lbl.setObjectName(_fromUtf8("avo_lbl"))
        self.gridLayout.addWidget(self.avo_lbl, 1, 1, 1, 1)
        self.fftf_lbl = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fftf_lbl.setFont(font)
        self.fftf_lbl.setObjectName(_fromUtf8("fftf_lbl"))
        self.gridLayout.addWidget(self.fftf_lbl, 2, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.curve_widget = TuningCurveEditor(self.frame)
        self.curve_widget.setObjectName(_fromUtf8("curve_widget"))
        self.verticalLayout_2.addWidget(self.curve_widget)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(CalibrationWidget)
        QtCore.QObject.connect(self.applycal_ckbx, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox.setEnabled)
        QtCore.QObject.connect(self.tc_radio, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CalibrationWidget)

    def retranslateUi(self, CalibrationWidget):
        CalibrationWidget.setWindowTitle(_translate("CalibrationWidget", "Form", None))
        self.savecal_ckbx.setText(_translate("CalibrationWidget", "Save calibration", None))
        self.applycal_ckbx.setText(_translate("CalibrationWidget", "Test calibration", None))
        self.groupBox.setTitle(_translate("CalibrationWidget", "Test type", None))
        self.tc_radio.setText(_translate("CalibrationWidget", "Tone Curve", None))
        self.noise_radio.setText(_translate("CalibrationWidget", "Noise", None))
        self.chirp_radio.setText(_translate("CalibrationWidget", "Sweep", None))
        self.aiv_lbl.setText(_translate("CalibrationWidget", "0", None))
        self.label2.setText(_translate("CalibrationWidget", "FFT peak :", None))
        self.label.setText(_translate("CalibrationWidget", "other:", None))
        self.flabel.setText(_translate("CalibrationWidget", "0", None))
        self.label0.setText(_translate("CalibrationWidget", "AO Voltage :", None))
        self.label3.setText(_translate("CalibrationWidget", "FFT at f :", None))
        self.label_10.setText(_translate("CalibrationWidget", "Frequency :", None))
        self.label_6.setText(_translate("CalibrationWidget", "0", None))
        self.fftpeak_lbl.setText(_translate("CalibrationWidget", "0", None))
        self.label_11.setText(_translate("CalibrationWidget", "Intensity :", None))
        self.dblabel.setText(_translate("CalibrationWidget", "0", None))
        self.db_lbl.setText(_translate("CalibrationWidget", "0", None))
        self.label4.setText(_translate("CalibrationWidget", "db SPL :", None))
        self.label1.setText(_translate("CalibrationWidget", "AI Voltage :", None))
        self.avo_lbl.setText(_translate("CalibrationWidget", "0", None))
        self.fftf_lbl.setText(_translate("CalibrationWidget", "0", None))

from spikeylab.stim.tceditor import TuningCurveEditor
