# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\calibration_widget.ui'
#
# Created: Wed Jan 29 16:34:12 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CalibrationWidget(object):
    def setupUi(self, CalibrationWidget):
        CalibrationWidget.setObjectName(_fromUtf8("CalibrationWidget"))
        CalibrationWidget.resize(541, 345)
        self.verticalLayout = QtGui.QVBoxLayout(CalibrationWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_11 = QtGui.QLabel(CalibrationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.dblabel = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dblabel.setFont(font)
        self.dblabel.setObjectName(_fromUtf8("dblabel"))
        self.gridLayout.addWidget(self.dblabel, 0, 4, 1, 1)
        self.label0 = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label0.setFont(font)
        self.label0.setObjectName(_fromUtf8("label0"))
        self.gridLayout.addWidget(self.label0, 1, 0, 1, 1)
        self.flabel = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.flabel.setFont(font)
        self.flabel.setObjectName(_fromUtf8("flabel"))
        self.gridLayout.addWidget(self.flabel, 0, 1, 1, 1)
        self.label = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 3, 1, 1)
        self.label2 = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(CalibrationWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_10 = QtGui.QLabel(CalibrationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(CalibrationWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 4, 1, 1)
        self.label3 = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label3.setFont(font)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(CalibrationWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 4, 1, 1)
        self.label_2 = QtGui.QLabel(CalibrationWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label1 = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(CalibrationWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label4 = QtGui.QLabel(CalibrationWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label4.setFont(font)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(CalibrationWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.curve_widget = TuningCurveEditor(CalibrationWidget)
        self.curve_widget.setObjectName(_fromUtf8("curve_widget"))
        self.verticalLayout.addWidget(self.curve_widget)
        self.calgroup = QtGui.QGroupBox(CalibrationWidget)
        self.calgroup.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setKerning(True)
        self.calgroup.setFont(font)
        self.calgroup.setTitle(_fromUtf8(""))
        self.calgroup.setFlat(False)
        self.calgroup.setCheckable(False)
        self.calgroup.setObjectName(_fromUtf8("calgroup"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.calgroup)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.savecal_ckbx = QtGui.QCheckBox(self.calgroup)
        self.savecal_ckbx.setObjectName(_fromUtf8("savecal_ckbx"))
        self.horizontalLayout_4.addWidget(self.savecal_ckbx)
        self.applycal_ckbx = QtGui.QCheckBox(self.calgroup)
        self.applycal_ckbx.setObjectName(_fromUtf8("applycal_ckbx"))
        self.horizontalLayout_4.addWidget(self.applycal_ckbx)
        self.verticalLayout.addWidget(self.calgroup)

        self.retranslateUi(CalibrationWidget)
        QtCore.QMetaObject.connectSlotsByName(CalibrationWidget)

    def retranslateUi(self, CalibrationWidget):
        CalibrationWidget.setWindowTitle(_translate("CalibrationWidget", "Form", None))
        self.label_11.setText(_translate("CalibrationWidget", "Intensity :", None))
        self.dblabel.setText(_translate("CalibrationWidget", "0", None))
        self.label0.setText(_translate("CalibrationWidget", "AO Voltage :", None))
        self.flabel.setText(_translate("CalibrationWidget", "0", None))
        self.label.setText(_translate("CalibrationWidget", "other:", None))
        self.label2.setText(_translate("CalibrationWidget", "FFT peak :", None))
        self.label_8.setText(_translate("CalibrationWidget", "0", None))
        self.label_10.setText(_translate("CalibrationWidget", "Frequency :", None))
        self.label_6.setText(_translate("CalibrationWidget", "0", None))
        self.label3.setText(_translate("CalibrationWidget", "FFT at f :", None))
        self.label_7.setText(_translate("CalibrationWidget", "0", None))
        self.label_2.setText(_translate("CalibrationWidget", "0", None))
        self.label1.setText(_translate("CalibrationWidget", "AI Voltage :", None))
        self.label_3.setText(_translate("CalibrationWidget", "0", None))
        self.label4.setText(_translate("CalibrationWidget", "db SPL :", None))
        self.label_4.setText(_translate("CalibrationWidget", "0", None))
        self.savecal_ckbx.setText(_translate("CalibrationWidget", "Save calibration", None))
        self.applycal_ckbx.setText(_translate("CalibrationWidget", "Apply calibration", None))

from spikeylab.stim.tceditor import TuningCurveEditor
